kz_kwiz_party:
    resource: "@KZKwizBundle/Controller/PartyController.php"
    type:     annotation

kz_kwiz:
    resource: "@KZKwizBundle/Resources/config/routing.yml"
    prefix:   /

kz_user:
    resource: "@KZUserBundle/Resources/config/routing.yml"
    prefix:   /
