<?php

namespace KZ\KwizBundle\Repository;

/**
 * PartyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartyRepository extends \Doctrine\ORM\EntityRepository
{
    public function countNbPlayer($id) {
        $query = $this->getEntityManager()->createQuery("SELECT COUNT(g) FROM KZKwizBundle:Game g WHERE g.id = :id");
        $query->setParameter('id', $id);

        return $query->getSingleScalarResult();
    }
}
